<#
.SYNOPSIS
    Generates README content for packages
.DESCRIPTION
    Creates package-specific README content
#>
function Get-PackageReadmeContent {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string]$AppName,
        [string]$AppVendor,
        [string]$AppVersion,
        [string]$AppArch,
        [string]$AppLang,
        [string]$Date,
        [string]$MsiFilename,
        [string]$ExeFilename
    )

    $installerInfo = if ($MsiFilename) {
        "Copy MSI to: Files\$MsiFilename"
    }
    else {
        "Copy EXE to: Files\$ExeFilename"
    }

    return @"
# $AppName - Autopilot Deployment Package

**Vendor:** $AppVendor
**Version:** $AppVersion
**Architecture:** $AppArch
**Language:** $AppLang
**Created:** $Date
**Author:** Christoph Ramböck (c@ramboeck.it)

---

## Quick Setup

### 1. Add PSAppDeployToolkit 4.1.5
``````
Download: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases
Extract to: PSAppDeployToolkit\
``````

### 2. Add Installer
``````
$installerInfo
``````

### 3. Test
``````powershell
.\Invoke-AppDeployToolkit.ps1 -DeployMode Silent
.\Detect-$($AppName.Replace(' ', '')).ps1
``````

### 4. Create IntuneWin
``````powershell
IntuneWinAppUtil.exe -c "." -s "Invoke-AppDeployToolkit.ps1" -o "Output"
``````

---

## Intune Configuration

**Install Command:**
``````
powershell.exe -ExecutionPolicy Bypass -File "Invoke-AppDeployToolkit.ps1" -DeploymentType "Install" -DeployMode "Silent"
``````

**Uninstall Command:**
``````
powershell.exe -ExecutionPolicy Bypass -File "Invoke-AppDeployToolkit.ps1" -DeploymentType "Uninstall" -DeployMode "Silent"
``````

**Detection Method:**
- Type: Custom Script
- Script: Detect-$($AppName.Replace(' ', '')).ps1
- Run as: System

---

**© 2025 Ramböck IT - Generated by Package Factory v2.1**
"@
}
